name: Sync Production Theme

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Download Production Theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE_URL }}
        run: |
          # Get production theme ID
          PROD_THEME=$(shopify theme list --json | jq -r '.[] | select(.role=="live") | .id')

          if [ -n "$PROD_THEME" ]; then
            echo "Downloading production theme..."
            shopify theme pull -t $PROD_THEME
          else
            echo "No production theme found"
            exit 1
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: sync production theme changes'
          title: 'Sync: Production Theme Changes'
          body: |
            This PR syncs changes from the production theme to staging.

            - Auto-generated to keep staging in sync with production
            - Contains customer content changes from the theme customizer
          branch: sync/production-changes
          base: staging
          labels: |
            sync
            automated
          draft: false
