name: Release

on:
  push:
    branches:
      - main
      - staging

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      # Allow the job to create releases and tags
      contents: write
      # Allow the job to read and write issues (required by semantic-release)
      issues: write
      # Allow the job to read and write pull requests (required by semantic-release)
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Shopify CLI
        run: |
          npm install -g @shopify/cli @shopify/theme

      - name: Authenticate with Shopify
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: shopify auth token ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: npx semantic-release
