name: Release Package

on:
  push:
    branches:
      - main
      - staging

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      # Allow the job to create releases and tags
      contents: write
      # Allow the job to read and write issues (required by semantic-release)
      issues: write
      # Allow the job to read and write pull requests (required by semantic-release)
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Verify the integrity of provenance attestations and registry signatures
        run: npm audit signatures

      - name: Run tests
        run: npm test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          npx semantic-release
